version: '3.8'
name: Sea Battle

services:
#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_DB=courseworkDB
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U admin -d courseworkDB"]
#      interval: 10s
#      timeout: 5s
#      retries: 5

  backend:
    build:
      context: ./PE_backend
    container_name: backend
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.0.5:5432/courseworkDB
      - SPRING_DATASOURCE_USERNAME=gen_user
      - SPRING_DATASOURCE_PASSWORD=K!*-I870YQpj2=
    ports:
      - "8080:443"
#    depends_on:
#      postgres:
#        condition: service_healthy

  frontend:
    build:
      context: ./pe_frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api

#volumes:
#  pgdata:
